[project]
name = "vigilant-potato"
version = "0.1.0"
description = "This is where we learn how to build UIs in python with the QT framework"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyqt6>=6.10.2",
    "pyside6>=6.10.1",
]
